# action.yaml
name: 'Issue to PDF'
description: 'A GitHub Action to monitor and convert issues into PDF files within your repository.'
author: 'Attie Retief'
branding:
  icon: 'file'
  color: 'green'
inputs:
  token:
    description: Personal access token
    required: true
  address:
    description: Company address to include on the cover page
    required: true
    default: "<strong>COMPANY</strong><br>Address line 1<br>Address line 2<br>Address line 3<br>Address line 4<br>Company web address"
  dest:
    required: false
    description: Destination path generated PDF file
    default: 'PDFs'
  logo:
    description: Company logo to include in the PDF file
    required: false
    default: logo
  css:
    description: CSS file to use for styling the markdown PDF
    required: false
    default: templates/spec.css

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: python -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
        echo "TOKEN=${{ inputs.token }}" >> $GITHUB_ENV
        echo "DEST=${{ inputs.dest }}" >> $GITHUB_ENV
        echo "ADDRESS=${{ inputs.address }}" >> $GITHUB_ENV
        echo "CSS=${{ inputs.css }}" >> $GITHUB_ENV
        echo "LOGO=${{ inputs.logo }}" >> $GITHUB_ENV
        echo "NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
        echo "TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
        echo "AUTHOR=${{ github.event.issue.user.login }}" >> $GITHUB_ENV
        echo "CREATED=${{ github.event.issue.created_at }}" >> $GITHUB_ENV
        echo "UPDATED=${{ github.event.issue.updated_at }}" >> $GITHUB_ENV
        echo "REPO=${{ github.event.repo }}" >> $GITHUB_ENV
        echo "LABELS=${{ github.event.issue.labels[0].name }},${{ github.event.issue.labels[1].name }},${{ github.event.issue.labels[2].name }}" >> $GITHUB_ENV
        echo "${{ github.event.issue.body }}" > body.md
        cp ${{ inputs.logo }} logo
      shell: bash
    - name: Generate the PDF
      id: make-pdf
      run: python ${{ github.action_path }}/src/make-pdf.py
      shell: bash

