name: Test Action
on:
  issues:
    types:
      - labeled
      - edited

jobs:
  issue-to-pdf:
    runs-on: ubuntu-latest
    name: issue-to-pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_KEY }}
      - name: Make-pdf
        id: make-pdf
        uses: ./
        with:
          token: ${{ secrets.PERSONAL_KEY }}
          address: "<strong>COMPANY</strong><br>Address line 1<br>Address line 2<br>Address line 3<br>Address line 4<br>Company web address"
          logo: "templates/logo.jpg"
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'pdf from gh issue'