name: Test Action
on:
  issues:
    types:
      - labeled
      - edited

jobs:
  issue-to-pdf:
    runs-on: ubuntu-latest
    name: issue-to-pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_KEY }}
      - name: Make-pdf
        id: make-pdf
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          token: ${{ secrets.PERSONAL_KEY }}
          title: "Technical Specification"
          address: "<strong>LINC</strong><br>5th Floor, Gihon Building<br>Sportica Crescent<br>Tygervalley<br>Belville<br>linc.co.za"
          logo: "templates/logo"
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'pdf from gh issue'